services:
    admin:
        build: .
        container_name: admin
        ports:
            - "8080:8080"
        restart: unless-stopped
        env_file: .env
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

